; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                  = 10200107-x86_64 macOS               
[ DataSettings ]
datatype                             = snNucleotide                        
containsCodingNuc                    = False                               
MissingBaseSymbol                    = ?                                   
IdenticalBaseSymbol                  = .                                   
GapSymbol                            = -                                   
Labelled Sites                       = All Sites                           
Labels to Include                    =                                     
[ ProcessTypes ]
ppSubPatternEstML                    = true                                
[ AnalysisSettings ]
Analysis                             = Substitution Pattern Estimation (ML)
Tree to Use                          = Automatic (Neighbor-joining tree)   
User Tree File                       = Not Applicable                      
Statistical Method                   = Maximum Likelihood                  
Substitution Model                   = ====================                
Substitutions Type                   = Nucleotide                          
Model/Method                         = Tamura-Nei model                    
Rates and Patterns                   = ====================                
Rates among Sites                    = Uniform Rates                       
No of Discrete Gamma Categories      = Not Applicable                      
Data Subset to Use                   = ====================                
Gaps/Missing Data Treatment          = Use all sites                       
Site Coverage Cutoff (%)             = Not Applicable                      
Branch Swap Filter                   = None                                
Has Time Limit                       = False                               
Maximum Execution Time               = -1                                  
